/**
 * State types — generated by tauri-specta from Rust structs.
 *
 * These are the runtime state types used by the Tauri app. Useful for:
 * - External agent UIs that receive state snapshots
 * - TypeScript tools that process ProjectState JSON
 *
 * NOTE: This module exports TYPE DECLARATIONS ONLY, not runtime code.
 * TAURI_INVOKE command functions are NOT exported here.
 *
 * @module @timeline/shared-types/state
 */

// ── Core project state ────────────────────────────────────────────────────────
export type {
  ProjectState,
  Project,
  ProjectMetadata as StateProjectMetadata,
  ProjectSettings as StateProjectSettings,
  ProjectCommand,
  ProjectEvent,
  // Timeline
  Timeline as StateTimeline,
  Track as StateTrack,
  TrackType as StateTrackType,
  Clip as StateClip,
  Keyframe,
  Transition as StateTransition,
  // Media
  MediaPool,
  MediaItem,
  MediaMetadata,
  MediaType,
  MediaBin,
  // Playback
  PlaybackState,
  // UI
  UiState,
  // Browser
  BrowserState,
  BrowserTab,
  // Chat
  ChatSession,
  ChatMessage,
  // Version control
  VersionInfo,
  // Clipboard
  ClipboardData,
  // Events
  EventEnvelope,
  // Resources
  EffectResource,
  FilterResource,
  TransitionResource,
  TemplateResource,
  StyleTemplateResource,
  SubtitleResource,
  ColorGradingPresetResource,
  // Applied resources
  AppliedEffect,
  AppliedFilter,
  AppliedTemplate,
  // Geometry
  Resolution as StateResolution,
} from "../../../src/types/generated/tauri-bindings"
