/**
 * Interfaces for YOLO recognition data shared by UI, core services and adapters.
 */

export interface YoloDetection {
  /** Optional detection id generated by recognition backends. */
  id?: string
  /** Detected object class. */
  class: string
  /** Optional backend class id. */
  classId?: number
  /** Recognition confidence in the 0..1 range. */
  confidence: number
  /** Relative bounding box in frame coordinates. */
  bbox: {
    x: number
    y: number
    width: number
    height: number
  }
  /** Optional tracking id across frames. */
  trackId?: number
}

export interface YoloFrameData {
  /** Optional source frame number. */
  frameNumber?: number
  /** Timestamp in seconds from the video start. */
  timestamp: number
  /** Detections for the frame. */
  detections: YoloDetection[]
}

export interface YoloVideoData {
  /** Video id. */
  videoId: string
  /** Video file name. */
  videoName: string
  /** Video file path. */
  videoPath: string
  /** Optional duration in seconds. */
  duration?: number
  /** Optional absolute start time as a Unix timestamp. */
  startTime?: number
  /** Recognition data by frames. */
  frames: YoloFrameData[]
  /** Recognition metadata. */
  metadata?: {
    model: string
    version: string
    processedAt: string
    fps?: number
    [key: string]: unknown
  }
}

export interface YoloVideoSummary {
  videoId: string
  videoName: string
  frameCount: number
  detectedClasses: string[]
  classCounts: Record<string, number>
  classTimeRanges: Record<string, Array<{ start: number; end: number }>>
}
