// АВТОГЕНЕРАЦИЯ — НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ.
// Контракт ProjectSchema для агента / фронта / внешних продуктов (M1 #120 / #104).
// Источник: `timeline-render --emit-schema` (JSON Schema из ts-schema, Rust serde).
// Регенерация: `bun run gen:schema-types`.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Соотношение сторон видео
 */
export type AspectRatio =
  | ("Ratio16x9" | "Ratio4x3" | "Ratio21x9" | "Ratio1x1" | "Ratio9x16")
  | {
      Custom: number;
    };
/**
 * Тип трека
 */
export type TrackType = "Video" | "Audio" | "Subtitle";
/**
 * Источник клипа
 */
export type ClipSource =
  | {
      File: string;
    }
  | "Generated"
  | {
      Stream: string;
    }
  | {
      Device: string;
    };
/**
 * Тип эффекта
 */
export type EffectType =
  | "Blur"
  | "Brightness"
  | "Contrast"
  | "Speed"
  | "Reverse"
  | "Grayscale"
  | "Sepia"
  | "Saturation"
  | "HueRotate"
  | "Vintage"
  | "Duotone"
  | "Noir"
  | "Cyberpunk"
  | "Dreamy"
  | "Infrared"
  | "Matrix"
  | "Arctic"
  | "Sunset"
  | "Lomo"
  | "Twilight"
  | "Neon"
  | "Invert"
  | "Vignette"
  | "FilmGrain"
  | "ChromaticAberration"
  | "LensFlare"
  | "Glow"
  | "Sharpen"
  | "NoiseReduction"
  | "Stabilization"
  | "AudioFadeIn"
  | "AudioFadeOut"
  | "AudioCrossfade"
  | "AudioEqualizer"
  | "AudioCompressor"
  | "AudioReverb"
  | "AudioDelay"
  | "AudioChorus"
  | "AudioDistortion"
  | "AudioNormalize"
  | "AudioDenoise"
  | "AudioPitch"
  | "AudioTempo"
  | "AudioDucking"
  | "AudioGate"
  | "AudioLimiter"
  | "AudioExpander"
  | "AudioPan"
  | "AudioStereoWidth"
  | "AudioHighpass"
  | "AudioLowpass"
  | "AudioBandpass"
  | "ColorCorrection"
  | "ChromaKey"
  | "Custom"
  | "AudioFade";
/**
 * Категория эффекта
 */
export type EffectCategory =
  | "ColorCorrection"
  | "Artistic"
  | "Vintage"
  | "Cinematic"
  | "Creative"
  | "Technical"
  | "Motion"
  | "Distortion";
/**
 * Сложность эффекта
 */
export type EffectComplexity = "Basic" | "Intermediate" | "Advanced";
/**
 * Теги эффектов
 */
export type EffectTag =
  | "Popular"
  | "Professional"
  | "BeginnerFriendly"
  | "Experimental"
  | "Retro"
  | "Modern"
  | "Dramatic"
  | "Subtle"
  | "Intense";
/**
 * Параметр эффекта
 */
export type EffectParameter =
  | {
      Float: number;
    }
  | {
      Int: number;
    }
  | {
      String: string;
    }
  | {
      Bool: boolean;
    }
  | {
      Color: number;
    }
  | {
      FloatArray: number[];
    }
  | {
      FilePath: string;
    };
/**
 * Категория перехода
 */
export type TransitionCategory =
  | "Basic"
  | "Dissolve"
  | "Slide"
  | "Wipe"
  | "ThreeD"
  | "Morph"
  | "Distortion"
  | "Geometric"
  | "Light"
  | "Particle"
  | "Special";
/**
 * Теги переходов
 */
export type TransitionTag =
  | "Smooth"
  | "Sharp"
  | "Elegant"
  | "Dynamic"
  | "Minimal"
  | "Dramatic"
  | "Modern"
  | "Classic"
  | "Creative"
  | "Fast"
  | "Slow";
/**
 * Сложность перехода
 */
export type TransitionComplexity = "Simple" | "Medium" | "Complex";
/**
 * Тип фильтра
 */
export type FilterType =
  | "Brightness"
  | "Contrast"
  | "Saturation"
  | "Hue"
  | "Blur"
  | "Sharpen"
  | "Vignette"
  | "Grain"
  | "Glow"
  | "ShadowsHighlights"
  | "WhiteBalance"
  | "Exposure"
  | "Curves"
  | "Levels"
  | "ColorBalance"
  | "Custom";
/**
 * Тип шаблона
 */
export type TemplateType = "Vertical" | "Horizontal" | "Diagonal" | "Grid" | "Custom";
/**
 * Режим подгонки контента
 */
export type FitMode = "Fill" | "Fit" | "Stretch" | "None";
/**
 * Выравнивание по горизонтали
 */
export type AlignX = "Left" | "Center" | "Right";
/**
 * Выравнивание по вертикали
 */
export type AlignY = "Top" | "Center" | "Bottom";
/**
 * Категория стильного шаблона
 */
export type StyleTemplateCategory = "Intro" | "Outro" | "LowerThird" | "Title" | "Transition" | "Overlay";
/**
 * Стиль шаблона
 */
export type StyleTemplateStyle = "Modern" | "Vintage" | "Minimal" | "Corporate" | "Creative" | "Cinematic";
/**
 * Тип элемента стильного шаблона
 */
export type StyleElementType = "Text" | "Image" | "Video" | "Shape" | "Line" | "Icon" | "Particles";
/**
 * Толщина шрифта
 */
export type FontWeight =
  | "Thin"
  | "ExtraLight"
  | "Light"
  | "Normal"
  | "Medium"
  | "SemiBold"
  | "Bold"
  | "ExtraBold"
  | "Black";
/**
 * Стиль шрифта
 */
export type FontStyle = "Normal" | "Italic" | "Oblique";
/**
 * Выравнивание текста
 */
export type TextAlign = "Left" | "Center" | "Right" | "Justify";
/**
 * Режим масштабирования изображения
 */
export type ObjectFit = "Cover" | "Contain" | "Fill" | "None" | "ScaleDown";
/**
 * Тип формы
 */
export type ShapeType = "Rectangle" | "Circle" | "Ellipse" | "Triangle" | "Star" | "Polygon" | "Line" | "Arrow";
/**
 * Тип анимации
 */
export type AnimationType =
  | "FadeIn"
  | "FadeOut"
  | "Slide"
  | "Scale"
  | "Rotate"
  | "Bounce"
  | "Shake"
  | "Pulse"
  | "Flicker"
  | "Typewriter"
  | "MotionPath"
  | "Morph"
  | "Parallax"
  | "Dissolve";
/**
 * Функция сглаживания анимации
 */
export type AnimationEasing =
  | "Linear"
  | "Ease"
  | "EaseIn"
  | "EaseOut"
  | "EaseInOut"
  | "Quad"
  | "Cubic"
  | "Quart"
  | "Quint"
  | "Sine"
  | "Expo"
  | "Circ"
  | "Elastic"
  | "Back"
  | "Bounce";
/**
 * Направление анимации
 */
export type AnimationDirection = "Normal" | "Reverse" | "Alternate" | "AlternateReverse";
/**
 * Позиция субтитра на экране
 */
export type SubtitlePosition =
  | {
      type: "Absolute";
      x: number;
      y: number;
    }
  | {
      type: "Relative";
      align_x: SubtitleAlignX;
      align_y: SubtitleAlignY;
    };
/**
 * Горизонтальное выравнивание субтитра
 */
export type SubtitleAlignX = "Left" | "Center" | "Right";
/**
 * Вертикальное выравнивание субтитра
 */
export type SubtitleAlignY = "Top" | "Center" | "Middle" | "Bottom";
/**
 * Толщина шрифта субтитра
 */
export type SubtitleFontWeight = "Thin" | "Light" | "Normal" | "Medium" | "Bold" | "Black";
/**
 * Тип анимации субтитра
 */
export type SubtitleAnimationType =
  | "FadeIn"
  | "FadeOut"
  | "SlideIn"
  | "SlideOut"
  | "ScaleIn"
  | "ScaleOut"
  | "Typewriter"
  | "Wave"
  | "Bounce"
  | "Shake"
  | "Blink"
  | "Dissolve"
  | "Scale";
/**
 * Функция сглаживания анимации субтитра
 */
export type SubtitleEasing = "Linear" | "Ease" | "EaseIn" | "EaseOut" | "EaseInOut" | "Elastic" | "Bounce";
/**
 * Направление анимации субтитра
 */
export type SubtitleDirection = "Top" | "Bottom" | "Left" | "Right" | "Center";
/**
 * Формат вывода видео
 */
export type OutputFormat =
  | ("Mp4" | "Avi" | "Mov" | "Mkv" | "WebM" | "Gif")
  | {
      Custom: string;
    };
/**
 * Формат превью
 */
export type PreviewFormat = "Jpeg" | "Png" | "WebP";

/**
 * Основная схема проекта Timeline Studio
 */
export interface ProjectSchema {
  /**
   * Версия схемы проекта для совместимости
   */
  version: string;
  /**
   * Метаданные проекта
   */
  metadata: ProjectMetadata;
  /**
   * Настройки timeline (fps, разрешение, длительность)
   */
  timeline: Timeline;
  /**
   * Список треков (видео, аудио, субтитры)
   */
  tracks: Track[];
  /**
   * Глобальные эффекты проекта
   */
  effects: Effect[];
  /**
   * Переходы между клипами
   */
  transitions: Transition[];
  /**
   * Фильтры для визуальных эффектов
   */
  filters: Filter[];
  /**
   * Шаблоны многокамерных раскладок
   */
  templates: Template[];
  /**
   * Стилестические шаблоны (интро, аутро, титры)
   */
  style_templates: StyleTemplate[];
  /**
   * Субтитры проекта
   */
  subtitles: Subtitle[];
  /**
   * Настройки проекта и экспорта
   */
  settings: ProjectSettings;
}
/**
 * Метаданные проекта
 */
export interface ProjectMetadata {
  /**
   * Название проекта
   */
  name: string;
  /**
   * Описание проекта
   */
  description?: string | null;
  /**
   * Время создания
   */
  created_at: string;
  /**
   * Время последней модификации
   */
  modified_at: string;
  /**
   * Автор проекта
   */
  author?: string | null;
}
/**
 * Настройки timeline
 */
export interface Timeline {
  /**
   * Общая продолжительность в секундах
   */
  duration: number;
  /**
   * Кадры в секунду
   */
  fps: number;
  /**
   * Разрешение видео (ширина, высота)
   *
   * @minItems 2
   * @maxItems 2
   */
  resolution: [number, number];
  /**
   * Частота дискретизации аудио
   */
  sample_rate: number;
  /**
   * Соотношение сторон
   */
  aspect_ratio: AspectRatio;
}
/**
 * Дорожка timeline (видео, аудио, субтитры)
 */
export interface Track {
  /**
   * Уникальный идентификатор трека
   */
  id: string;
  /**
   * Тип трека
   */
  track_type: TrackType;
  /**
   * Название трека
   */
  name: string;
  /**
   * Включен ли трек
   */
  enabled: boolean;
  /**
   * Громкость трека (0.0 - 1.0)
   */
  volume: number;
  /**
   * Заблокирован ли трек для редактирования
   */
  locked: boolean;
  /**
   * Список клипов в треке
   */
  clips: Clip[];
  /**
   * ID эффектов, применяемых ко всему треку
   */
  effects: string[];
  /**
   * ID фильтров, применяемых ко всему треку
   */
  filters: string[];
}
/**
 * Медиаклип на треке
 */
export interface Clip {
  /**
   * Уникальный идентификатор клипа
   */
  id: string;
  /**
   * Источник клипа
   */
  source: ClipSource;
  /**
   * Время начала клипа на timeline
   */
  start_time: number;
  /**
   * Время окончания клипа на timeline
   */
  end_time: number;
  /**
   * Время начала в исходном файле
   */
  source_start: number;
  /**
   * Время окончания в исходном файле
   */
  source_end: number;
  /**
   * Скорость воспроизведения (1.0 = нормальная)
   */
  speed: number;
  /**
   * Прозрачность (0.0 - 1.0)
   */
  opacity: number;
  /**
   * ID эффектов, применяемых к клипу
   */
  effects: string[];
  /**
   * ID фильтров, применяемых к клипу
   */
  filters: string[];
  /**
   * ID шаблона раскладки (для многокамерных эффектов)
   */
  template_id?: string | null;
  /**
   * Позиция клипа в шаблоне
   */
  template_position?: number | null;
  /**
   * Настройки цветокоррекции
   */
  color_correction?: ColorCorrection | null;
  /**
   * Настройки обрезки (кроп)
   */
  crop?: CropSettings | null;
  /**
   * Настройки трансформации
   */
  transform?: TransformSettings | null;
  /**
   * Альтернативный аудио трек
   */
  audio_track_index?: number | null;
  /**
   * Дополнительные свойства клипа
   */
  properties: ClipProperties;
}
/**
 * Настройки цветокоррекции
 */
export interface ColorCorrection {
  brightness: number;
  contrast: number;
  saturation: number;
  hue: number;
  gamma: number;
  highlights: number;
  shadows: number;
  whites: number;
  blacks: number;
}
/**
 * Настройки обрезки (кроп)
 */
export interface CropSettings {
  left: number;
  top: number;
  right: number;
  bottom: number;
}
/**
 * Настройки трансформации
 */
export interface TransformSettings {
  scale_x: number;
  scale_y: number;
  position_x: number;
  position_y: number;
  rotation: number;
  anchor_x: number;
  anchor_y: number;
}
/**
 * Дополнительные свойства клипа
 */
export interface ClipProperties {
  /**
   * Заметки о клипе
   */
  notes?: string | null;
  /**
   * Теги для поиска и организации
   */
  tags: string[];
  /**
   * Пользовательские метаданные
   */
  custom_metadata: {
    [k: string]: unknown;
  };
}
/**
 * Эффект, применяемый к клипу или треку
 */
export interface Effect {
  /**
   * Уникальный идентификатор эффекта
   */
  id: string;
  /**
   * Тип эффекта (строка для расширяемости)
   */
  effect_type: EffectType;
  /**
   * Название эффекта
   */
  name: string;
  /**
   * Категория эффекта
   */
  category?: EffectCategory | null;
  /**
   * Сложность эффекта
   */
  complexity?: EffectComplexity | null;
  /**
   * Теги эффекта
   */
  tags: EffectTag[];
  /**
   * Описание эффекта (локализованное)
   */
  description?: {
    [k: string]: string;
  } | null;
  /**
   * Метки эффекта (локализованные)
   */
  labels?: {
    [k: string]: string;
  } | null;
  /**
   * Включен ли эффект
   */
  enabled: boolean;
  /**
   * Параметры эффекта
   */
  parameters: {
    [k: string]: EffectParameter;
  };
  /**
   * Время начала эффекта (для анимации)
   */
  start_time?: number | null;
  /**
   * Время окончания эффекта (для анимации)
   */
  end_time?: number | null;
  /**
   * FFmpeg команда (в виде шаблона)
   */
  ffmpeg_command?: string | null;
  /**
   * CSS фильтр (в виде шаблона)
   */
  css_filter?: string | null;
  /**
   * Путь к превью
   */
  preview_path?: string | null;
  /**
   * Пресеты эффекта
   */
  presets?: {
    [k: string]: EffectPreset;
  } | null;
}
/**
 * Пресет эффекта
 */
export interface EffectPreset {
  /**
   * Название пресета (локализованное)
   */
  name: {
    [k: string]: string;
  };
  /**
   * Параметры пресета
   */
  params: {
    [k: string]: EffectParameter;
  };
  /**
   * Описание пресета (локализованное)
   */
  description: {
    [k: string]: string;
  };
}
/**
 * Переход между клипами
 */
export interface Transition {
  /**
   * Уникальный идентификатор перехода
   */
  id: string;
  /**
   * Тип перехода
   */
  transition_type: string;
  /**
   * Название перехода
   */
  name: string;
  /**
   * Длительность перехода
   */
  duration: TransitionDuration;
  /**
   * Категория перехода
   */
  category?: TransitionCategory | null;
  /**
   * Теги перехода
   */
  tags: TransitionTag[];
  /**
   * Сложность перехода
   */
  complexity?: TransitionComplexity | null;
  /**
   * Включен ли переход
   */
  enabled: boolean;
  /**
   * Параметры перехода
   */
  parameters: {
    [k: string]: unknown;
  };
  /**
   * FFmpeg команда для перехода
   */
  ffmpeg_command?: string | null;
  /**
   * Кривая плавности перехода
   */
  easing?: string | null;
  /**
   * Направление перехода
   */
  direction?: string | null;
}
/**
 * Длительность перехода
 */
export interface TransitionDuration {
  /**
   * Основная длительность в секундах
   */
  value: number;
  /**
   * Минимальная длительность
   */
  min?: number | null;
  /**
   * Максимальная длительность
   */
  max?: number | null;
}
/**
 * Фильтр для визуальных эффектов
 */
export interface Filter {
  /**
   * Уникальный идентификатор фильтра
   */
  id: string;
  /**
   * Тип фильтра
   */
  filter_type: FilterType;
  /**
   * Название фильтра
   */
  name: string;
  /**
   * Включен ли фильтр
   */
  enabled: boolean;
  /**
   * Параметры фильтра (числовые значения)
   */
  parameters: {
    [k: string]: number;
  };
  /**
   * FFmpeg команда для применения фильтра
   */
  ffmpeg_command?: string | null;
  /**
   * Интенсивность фильтра (для обратной совместимости)
   */
  intensity: number;
  /**
   * Пользовательский фильтр (для обратной совместимости)
   */
  custom_filter?: string | null;
}
/**
 * Шаблон многокамерной раскладки
 */
export interface Template {
  /**
   * Уникальный идентификатор шаблона
   */
  id: string;
  /**
   * Тип шаблона
   */
  template_type: TemplateType;
  /**
   * Название шаблона
   */
  name: string;
  /**
   * Количество видео в шаблоне
   */
  screens: number;
  /**
   * Ячейки шаблона с позициями
   */
  cells: TemplateCell[];
  /**
   * Регионы шаблона (для обратной совместимости)
   */
  regions: TemplateRegion[];
}
/**
 * Ячейка шаблона
 */
export interface TemplateCell {
  /**
   * Индекс ячейки (0-based)
   */
  index: number;
  /**
   * Позиция X в процентах (0-100)
   */
  x: number;
  /**
   * Позиция Y в процентах (0-100)
   */
  y: number;
  /**
   * Ширина в процентах (0-100)
   */
  width: number;
  /**
   * Высота в процентах (0-100)
   */
  height: number;
  /**
   * Режим масштабирования видео
   */
  fit_mode: FitMode;
  /**
   * Горизонтальное выравнивание
   */
  align_x: AlignX;
  /**
   * Вертикальное выравнивание
   */
  align_y: AlignY;
  /**
   * Дополнительное масштабирование (1.0 = 100%)
   */
  scale?: number | null;
}
/**
 * Регион шаблона (для обратной совместимости)
 */
export interface TemplateRegion {
  x: number;
  y: number;
  width: number;
  height: number;
  padding: number;
}
/**
 * Стильный шаблон (интро, аутро, титры)
 */
export interface StyleTemplate {
  /**
   * Уникальный идентификатор шаблона
   */
  id: string;
  /**
   * Название шаблона
   */
  name: string;
  /**
   * Категория шаблона
   */
  category: StyleTemplateCategory;
  /**
   * Стиль шаблона
   */
  style: StyleTemplateStyle;
  /**
   * Длительность в секундах
   */
  duration: number;
  /**
   * Элементы шаблона
   */
  elements: StyleTemplateElement[];
  /**
   * Цвет фона (для обратной совместимости)
   */
  background_color: string;
  /**
   * Переходы (для обратной совместимости)
   */
  transitions: unknown[];
}
/**
 * Элемент стильного шаблона
 */
export interface StyleTemplateElement {
  /**
   * Уникальный идентификатор элемента
   */
  id: string;
  /**
   * Тип элемента
   */
  element_type: StyleElementType;
  /**
   * Название элемента
   */
  name: string;
  /**
   * Позиция элемента
   */
  position: Position2D;
  /**
   * Размер элемента
   */
  size: Size2D;
  /**
   * Временные параметры
   */
  timing: ElementTiming;
  /**
   * Свойства элемента
   */
  properties: StyleElementProperties;
  /**
   * Анимации элемента
   */
  animations: ElementAnimation[];
  /**
   * Контент элемента (для обратной совместимости)
   */
  content: string;
  /**
   * Стиль элемента (для обратной совместимости)
   */
  style?: ElementStyle | null;
}
/**
 * Позиция в 2D пространстве
 */
export interface Position2D {
  x: number;
  y: number;
}
/**
 * Размер в 2D пространстве
 */
export interface Size2D {
  width: number;
  height: number;
}
/**
 * Временные параметры элемента
 */
export interface ElementTiming {
  /**
   * Время появления в секундах
   */
  in_time: number;
  /**
   * Время исчезновения в секундах
   */
  out_time: number;
  /**
   * Длительность в секундах
   */
  duration: number;
}
/**
 * Свойства элемента стильного шаблона
 */
export interface StyleElementProperties {
  /**
   * Текстовое содержимое (для текстовых элементов)
   */
  text?: string | null;
  /**
   * Семейство шрифта
   */
  font_family?: string | null;
  /**
   * Размер шрифта
   */
  font_size?: number | null;
  /**
   * Толщина шрифта
   */
  font_weight?: FontWeight | null;
  /**
   * Стиль шрифта
   */
  font_style?: FontStyle | null;
  /**
   * Цвет текста
   */
  text_color?: string | null;
  /**
   * Выравнивание текста
   */
  text_align?: TextAlign | null;
  /**
   * Цвет заливки
   */
  fill_color?: string | null;
  /**
   * Цвет обводки
   */
  stroke_color?: string | null;
  /**
   * Толщина обводки
   */
  stroke_width?: number | null;
  /**
   * Прозрачность
   */
  opacity?: number | null;
  /**
   * Поворот в градусах
   */
  rotation?: number | null;
  /**
   * Масштаб
   */
  scale?: number | null;
  /**
   * Тень
   */
  shadow?: ShadowProperties | null;
  /**
   * Размытие
   */
  blur?: number | null;
  /**
   * Путь к изображению (для изображений)
   */
  image_path?: string | null;
  /**
   * Режим масштабирования изображения
   */
  object_fit?: ObjectFit | null;
  /**
   * Тип формы (для форм)
   */
  shape_type?: ShapeType | null;
  /**
   * Радиус скругления углов
   */
  border_radius?: number | null;
  /**
   * Дополнительные свойства
   */
  custom: {
    [k: string]: unknown;
  };
}
/**
 * Свойства тени
 */
export interface ShadowProperties {
  /**
   * Смещение по X
   */
  offset_x: number;
  /**
   * Смещение по Y
   */
  offset_y: number;
  /**
   * Размытие
   */
  blur: number;
  /**
   * Распространение
   */
  spread: number;
  /**
   * Цвет
   */
  color: string;
}
/**
 * Анимация элемента
 */
export interface ElementAnimation {
  /**
   * Уникальный идентификатор анимации
   */
  id: string;
  /**
   * Тип анимации
   */
  animation_type: AnimationType;
  /**
   * Длительность в секундах
   */
  duration: number;
  /**
   * Задержка в секундах
   */
  delay: number;
  /**
   * Функция сглаживания
   */
  easing: AnimationEasing;
  /**
   * Количество повторений (0 = бесконечно)
   */
  repeat: number;
  /**
   * Направление анимации
   */
  direction: AnimationDirection;
  /**
   * Дополнительные свойства анимации
   */
  properties: {
    [k: string]: unknown;
  };
}
/**
 * Стиль элемента (для обратной совместимости)
 */
export interface ElementStyle {
  font_family?: string | null;
  font_size?: number | null;
  color?: string | null;
  background_color?: string | null;
}
/**
 * Субтитр
 */
export interface Subtitle {
  /**
   * Уникальный идентификатор субтитра
   */
  id: string;
  /**
   * Текст субтитра
   */
  text: string;
  /**
   * Время начала в секундах
   */
  start_time: number;
  /**
   * Время окончания в секундах
   */
  end_time: number;
  /**
   * Позиция субтитра на экране
   */
  position: SubtitlePosition;
  /**
   * Стиль субтитра
   */
  style: SubtitleStyle;
  /**
   * Включен ли субтитр
   */
  enabled: boolean;
  /**
   * Анимации субтитра
   */
  animations: SubtitleAnimation[];
  /**
   * Семейство шрифта
   */
  font_family: string;
  /**
   * Размер шрифта
   */
  font_size: number;
  /**
   * Цвет текста
   */
  color: string;
  /**
   * Прозрачность
   */
  opacity: number;
  /**
   * Жирность шрифта
   */
  font_weight: SubtitleFontWeight;
  /**
   * Тень
   */
  shadow: boolean;
  /**
   * Обводка
   */
  outline: boolean;
  /**
   * Длительность (вычисляется)
   */
  duration: number;
}
/**
 * Стиль субтитра
 */
export interface SubtitleStyle {
  /**
   * Название шрифта
   */
  font_family: string;
  /**
   * Размер шрифта в пикселях
   */
  font_size: number;
  /**
   * Толщина шрифта
   */
  font_weight: SubtitleFontWeight;
  /**
   * Цвет текста (в формате #RRGGBB или #RRGGBBAA)
   */
  color: string;
  /**
   * Цвет обводки (опционально)
   */
  stroke_color?: string | null;
  /**
   * Толщина обводки в пикселях
   */
  stroke_width: number;
  /**
   * Цвет тени (опционально)
   */
  shadow_color?: string | null;
  /**
   * Смещение тени по X
   */
  shadow_x: number;
  /**
   * Смещение тени по Y
   */
  shadow_y: number;
  /**
   * Размытие тени
   */
  shadow_blur: number;
  /**
   * Цвет фона (опционально)
   */
  background_color?: string | null;
  /**
   * Прозрачность фона (0-1)
   */
  background_opacity: number;
  /**
   * Отступы текста внутри фона
   */
  padding: SubtitlePadding;
  /**
   * Радиус скругления фона
   */
  border_radius: number;
  /**
   * Межстрочный интервал
   */
  line_height: number;
  /**
   * Межбуквенный интервал
   */
  letter_spacing: number;
  /**
   * Максимальная ширина в процентах
   */
  max_width: number;
}
/**
 * Отступы текста внутри фона субтитра
 */
export interface SubtitlePadding {
  /**
   * Отступ сверху
   */
  top: number;
  /**
   * Отступ справа
   */
  right: number;
  /**
   * Отступ снизу
   */
  bottom: number;
  /**
   * Отступ слева
   */
  left: number;
}
/**
 * Анимация субтитра
 */
export interface SubtitleAnimation {
  /**
   * Уникальный идентификатор анимации
   */
  id: string;
  /**
   * Тип анимации
   */
  animation_type: SubtitleAnimationType;
  /**
   * Длительность анимации в секундах
   */
  duration: number;
  /**
   * Задержка перед началом анимации
   */
  delay: number;
  /**
   * Функция сглаживания
   */
  easing: SubtitleEasing;
  /**
   * Направление анимации (для движения)
   */
  direction?: SubtitleDirection | null;
  /**
   * Дополнительные параметры
   */
  properties: {
    [k: string]: unknown;
  };
  /**
   * Время начала анимации (для обратной совместимости)
   */
  start_time: number;
}
/**
 * Настройки проекта
 */
export interface ProjectSettings {
  /**
   * Настройки экспорта
   */
  export: ExportSettings;
  /**
   * Настройки превью
   */
  preview: PreviewSettings;
  /**
   * Пользовательские настройки
   */
  custom: {
    [k: string]: unknown;
  };
  /**
   * Настройки вывода (для обратной совместимости)
   */
  output: OutputSettings;
  /**
   * Разрешение (для обратной совместимости)
   */
  resolution: Resolution;
  /**
   * Частота кадров (для обратной совместимости)
   */
  frame_rate: number;
  /**
   * Соотношение сторон (для обратной совместимости)
   */
  aspect_ratio: AspectRatio;
}
/**
 * Настройки экспорта
 */
export interface ExportSettings {
  /**
   * Формат вывода
   */
  format: OutputFormat;
  /**
   * Качество (от 1 до 100)
   */
  quality: number;
  /**
   * Битрейт видео (kbps)
   */
  video_bitrate: number;
  /**
   * Битрейт аудио (kbps)
   */
  audio_bitrate: number;
  /**
   * Использовать аппаратное ускорение
   */
  hardware_acceleration: boolean;
  /**
   * Предпочитаемый GPU кодировщик (опционально)
   */
  preferred_gpu_encoder?: string | null;
  /**
   * Дополнительные параметры FFmpeg
   */
  ffmpeg_args: string[];
  /**
   * Профиль кодирования
   */
  encoding_profile?: string | null;
  /**
   * Режим контроля битрейта
   */
  rate_control_mode?: string | null;
  /**
   * Интервал ключевых кадров (GOP size)
   */
  keyframe_interval?: number | null;
  /**
   * Количество B-кадров
   */
  b_frames?: number | null;
  /**
   * Количество проходов кодирования (1 или 2)
   */
  multi_pass?: number | null;
  /**
   * Пресет скорости кодирования
   */
  preset?: string | null;
  /**
   * Максимальный битрейт
   */
  max_bitrate?: number | null;
  /**
   * Минимальный битрейт
   */
  min_bitrate?: number | null;
  /**
   * CRF значение (0-51)
   */
  crf?: number | null;
  /**
   * Оптимизация для скорости
   */
  optimize_for_speed?: boolean | null;
  /**
   * Оптимизация для сети
   */
  optimize_for_network?: boolean | null;
  /**
   * Нормализация аудио
   */
  normalize_audio?: boolean | null;
  /**
   * Целевой уровень аудио в LKFS
   */
  audio_target?: number | null;
  /**
   * Пиковый уровень аудио в dBTP
   */
  audio_peak?: number | null;
}
/**
 * Настройки превью
 */
export interface PreviewSettings {
  /**
   * Разрешение превью
   *
   * @minItems 2
   * @maxItems 2
   */
  resolution: [number, number];
  /**
   * Качество превью (от 1 до 100)
   */
  quality: number;
  /**
   * FPS превью
   */
  fps: number;
  /**
   * Формат превью
   */
  format: PreviewFormat;
}
/**
 * Настройки вывода (для обратной совместимости)
 */
export interface OutputSettings {
  /**
   * Формат вывода
   */
  format: OutputFormat;
  /**
   * Качество (от 0 до 100)
   */
  quality: number;
  /**
   * Видео битрейт в kbps
   */
  video_bitrate?: number | null;
  /**
   * Аудио битрейт в kbps
   */
  audio_bitrate?: number | null;
  /**
   * Длительность вывода
   */
  duration: number;
}
/**
 * Разрешение видео
 */
export interface Resolution {
  width: number;
  height: number;
}
