/**
 * Core Module
 *
 * Ядро приложения - не зависит от конкретной платформы (Tauri, Browser, Node.js).
 * Содержит:
 * - Ports: интерфейсы для взаимодействия с внешними системами
 * - Types: типы данных (команды, события, состояние)
 * - Container: DI контейнер для управления зависимостями
 */

// Container (DI)
export {
  container,
  getBackend,
  getEnhancedSubtitleAutomation,
  getLanguage,
  getModal,
  getNodeBackend,
  getPlatform,
  getStorage,
  getTranscription,
  getUpdate,
  getUserSettings,
  resetContainer,
} from "./container"
// Ports (Interfaces)
export type {
  AIProjectEditCommand,
  AIProjectEditCommandType,
  AIProjectEditDiagnostic,
  AIProjectEditDiagnosticLevel,
  AIProjectEditorRequest,
  AIProjectEditorResult,
  AIProjectEditRepairContext,
  AIProjectEditRevisionSummary,
  AIProjectEditValidationError,
  BotFeedbackMediaKind,
  BotFeedbackTranscriptionProvider,
  BotFeedbackTranscriptionRequest,
  BotFeedbackTranscriptionResult,
  BotFirstCutGeneratorRequest,
  BotFirstCutGeneratorResult,
  BotFirstCutPlannerResult,
  BotFirstCutProvider,
  IAIProjectEditor,
  IBackendService,
  IBotFeedbackTranscriber,
  IBotFirstCutGenerator,
  IBotFirstCutPlanner,
  IEnhancedSubtitleAutomationService,
  ILanguageService,
  IModalService,
  INodeBackendService,
  IPlatformService,
  IPublishService,
  IRenderJobService,
  IScriptGenerator,
  IScriptPlanner,
  IStorageService,
  ITranscriptionService,
  IUpdateService,
  IUserSettingsService,
  NodeBackendHealth,
  NotificationOptions,
  OpenDialogOptions,
  SaveDialogOptions,
  ScriptDraft,
  ScriptGeneratorProvider,
  ScriptGeneratorRequest,
  ScriptGeneratorResult,
  ScriptPlannerResult,
  ScriptScene,
  ScriptSource,
  TranscriptionResult,
  Unsubscribe,
} from "./ports"
export type {
  AIProjectEditRunOptions,
  AIProjectEditRunResult,
  BotDestinationCapabilityRegistryOptions,
  BotEditSessionCreateOptions,
  BotEditSessionMergeOptions,
  BotFirstCutGeneratorOptions,
  BotRenderJobRetryOptions,
  BotWorkflowDraftMergeOptions,
  BotWorkflowRunnerOptions,
  LanguageResponse,
  ParsedBotWorkflowText,
  ScriptGeneratorOptions,
  TelegramLikeBotWorkflowRunnerOptions,
} from "./services"
export {
  canCancelBotRenderJob,
  canRetryBotRenderJob,
  cloneProjectSchema,
  compareBotEditSessionsByUpdatedAtDesc,
  createBotDestinationCapabilityRegistry,
  createBotEditRevisionId,
  createBotEditSessionFromWorkflow,
  createBotEditSessionId,
  createBotProjectSchemaFromRenderJob,
  createBotRenderJobRequest,
  createBotRenderJobRetryRequest,
  createBotRenderJobSnapshot,
  createBotWorkflowDraftId,
  createBotWorkflowRequestFromTelegramLikePayload,
  createBotWorkflowStatusEventSink,
  createBotWorkflowStatusMessage,
  createDeterministicFirstCutProject,
  createDeterministicScriptDraft,
  generateScriptSubtitles,
  createNoopBotMediaResolver,
  createTelegramLikeBotWorkflow,
  DefaultBotFirstCutGenerator,
  DefaultScriptGenerator,
  describeScriptDraftAsGoal,
  defaultBotWorkflowStatusText,
  formatAvailableBotDestinations,
  getAppLanguage,
  InMemoryBotRenderJobEventStream,
  isBotEditSessionActive,
  matchesBotEditSessionQuery,
  mergeBotEditSessionWorkflow,
  mergeBotWorkflowDraft,
  mergeBotWorkflowRequests,
  parseBotWorkflowText,
  resolveBotRenderJobMedia,
  runAIProjectEdit,
  runBotWorkflow,
  runTelegramLikeBotWorkflow,
  sendBotWorkflowValidationStatus,
  setAppLanguage,
  normalizeScriptDraft,
  validateAIProjectEditRequest,
  validateAIProjectEditResult,
  validateBotDestinationCapability,
  validateProjectSchemaShape,
  validateScriptDraftShape,
  withBotProjectSchema,
} from "./services"

// Types (re-exported from generated bindings for now)
export type {
  BotDestinationCapability,
  BotDestinationCapabilityRegistry,
  BotDestinationCapabilityStatus,
  BotEditRevision,
  BotEditSession,
  BotEditSessionQuery,
  BotEditSessionStatus,
  BotEditSessionStore,
  BotMediaAttachment,
  BotMediaAttachmentType,
  BotMediaResolveContext,
  BotMediaResolver,
  BotProjectAssemblyOptions,
  BotProjectAssemblyResolution,
  BotPublishMetadata,
  BotPublishRequest,
  BotPublishResult,
  BotPublishStatus,
  BotRenderJob,
  BotRenderJobArtifact,
  BotRenderJobDestination,
  BotRenderJobEvent,
  BotRenderJobEventQuery,
  BotRenderJobEventSink,
  BotRenderJobEventStreamOptions,
  BotRenderJobMediaInput,
  BotRenderJobProjectInput,
  BotRenderJobReconnectState,
  BotRenderJobRequest,
  BotRenderJobResult,
  BotRenderJobRunOptions,
  BotRenderJobSnapshot,
  BotRenderJobSource,
  BotRenderJobStatus,
  BotTemplateSelection,
  BotWorkflowApprovalGateOptions,
  BotWorkflowApprovalGateResult,
  BotWorkflowDraft,
  BotWorkflowDraftStore,
  BotWorkflowIntakeOptions,
  BotWorkflowIntakeResult,
  BotWorkflowOutput,
  BotWorkflowRequest,
  BotWorkflowRunOptions,
  BotWorkflowRunResult,
  BotWorkflowSource,
  BotWorkflowStatusFormatter,
  BotWorkflowStatusFormatterContext,
  BotWorkflowStatusKind,
  BotWorkflowStatusMessage,
  BotWorkflowStatusOptions,
  BotWorkflowStatusPolicy,
  BotWorkflowStatusSink,
  BotWorkflowValidationCode,
  BotWorkflowValidationError,
  BrowserState,
  BrowserTab,
  Clip,
  CommandResult,
  EventEnvelope,
  MediaFile,
  MediaItem,
  Project,
  ProjectCommand,
  ProjectEvent,
  ProjectSettings,
  ProjectState,
  TabSettings,
  TelegramLikeBotFile,
  TelegramLikeBotPayload,
  Timeline,
  Track,
  ViewMode,
} from "./types"
