/**
 * Core Module
 *
 * Ядро приложения - не зависит от конкретной платформы (Tauri, Browser, Node.js).
 * Содержит:
 * - Ports: интерфейсы для взаимодействия с внешними системами
 * - Types: типы данных (команды, события, состояние)
 * - Container: DI контейнер для управления зависимостями
 */

// Container (DI)
export {
  container,
  getBackend,
  getLanguage,
  getNodeBackend,
  getPlatform,
  getStorage,
  resetContainer,
} from "./container"
// Ports (Interfaces)
export type {
  IBackendService,
  ILanguageService,
  INodeBackendService,
  IPlatformService,
  IPublishService,
  IRenderJobService,
  IStorageService,
  NodeBackendHealth,
  NotificationOptions,
  OpenDialogOptions,
  SaveDialogOptions,
  Unsubscribe,
} from "./ports"
export type {
  BotRenderJobRetryOptions,
  BotWorkflowDraftMergeOptions,
  BotWorkflowRunnerOptions,
  LanguageResponse,
  ParsedBotWorkflowText,
  TelegramLikeBotWorkflowRunnerOptions,
} from "./services"
export {
  canCancelBotRenderJob,
  canRetryBotRenderJob,
  createBotProjectSchemaFromRenderJob,
  createBotRenderJobRequest,
  createBotRenderJobRetryRequest,
  createBotRenderJobSnapshot,
  createBotWorkflowDraftId,
  createBotWorkflowRequestFromTelegramLikePayload,
  createBotWorkflowStatusEventSink,
  createBotWorkflowStatusMessage,
  createNoopBotMediaResolver,
  createTelegramLikeBotWorkflow,
  defaultBotWorkflowStatusText,
  getAppLanguage,
  InMemoryBotRenderJobEventStream,
  mergeBotWorkflowDraft,
  mergeBotWorkflowRequests,
  parseBotWorkflowText,
  resolveBotRenderJobMedia,
  runBotWorkflow,
  runTelegramLikeBotWorkflow,
  sendBotWorkflowValidationStatus,
  setAppLanguage,
  withBotProjectSchema,
} from "./services"

// Types (re-exported from generated bindings for now)
export type {
  BotMediaAttachment,
  BotMediaAttachmentType,
  BotMediaResolveContext,
  BotMediaResolver,
  BotProjectAssemblyOptions,
  BotProjectAssemblyResolution,
  BotPublishMetadata,
  BotPublishRequest,
  BotPublishResult,
  BotPublishStatus,
  BotRenderJob,
  BotRenderJobArtifact,
  BotRenderJobDestination,
  BotRenderJobEvent,
  BotRenderJobEventQuery,
  BotRenderJobEventSink,
  BotRenderJobEventStreamOptions,
  BotRenderJobMediaInput,
  BotRenderJobProjectInput,
  BotRenderJobReconnectState,
  BotRenderJobRequest,
  BotRenderJobResult,
  BotRenderJobRunOptions,
  BotRenderJobSnapshot,
  BotRenderJobSource,
  BotRenderJobStatus,
  BotTemplateSelection,
  BotWorkflowDraft,
  BotWorkflowDraftStore,
  BotWorkflowIntakeOptions,
  BotWorkflowIntakeResult,
  BotWorkflowOutput,
  BotWorkflowRequest,
  BotWorkflowRunOptions,
  BotWorkflowRunResult,
  BotWorkflowSource,
  BotWorkflowStatusFormatter,
  BotWorkflowStatusFormatterContext,
  BotWorkflowStatusKind,
  BotWorkflowStatusMessage,
  BotWorkflowStatusOptions,
  BotWorkflowStatusPolicy,
  BotWorkflowStatusSink,
  BotWorkflowValidationCode,
  BotWorkflowValidationError,
  BrowserState,
  BrowserTab,
  Clip,
  CommandResult,
  EventEnvelope,
  MediaFile,
  MediaItem,
  Project,
  ProjectCommand,
  ProjectEvent,
  ProjectSettings,
  ProjectState,
  TabSettings,
  TelegramLikeBotFile,
  TelegramLikeBotPayload,
  Timeline,
  Track,
  ViewMode,
} from "./types"
